apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  labels:
    app: chrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - name: chrome
        image: us-central1-docker.pkg.dev/algorinfo99/docker-repo/chrome_crawler:0.5.2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3000
          name: chrome-svc
        env:
          - name: WEB_ADDR
            value: "0.0.0.0"
          - name: JWT_SECRET
            value: "/secrets/public.key"
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: chrome
            items:
              - key: private
                path: private.key
              - key: public
                path: public.key

---
apiVersion: v1
kind: Service
metadata:
  name: chrome-service
  labels:
    app: chrome
spec:
  type: ClusterIP
  # type: NodePort
  ports:
   - port: 80
     targetPort: chrome-svc
  selector:
   app: chrome

